apiVersion: batch/v1
kind: CronJob
metadata:
  name: remindmejob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      startingDeadlineSeconds: 100
      template:
        spec:
          containers:
          - name: remindmejob
            image: kubernetessuccinctly/remind-me-job:1.0.0 
---
